services:
  postgresql:
    image: postgres
    container_name: mypostgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
